/**
 * Electron main process for `npm run dev:electron`. Waits for the vite dev server (spawned in
 * parallel by `packages/scripts/src/start.script.ts`) to come up, then opens a BrowserWindow
 * pointing at it. The page itself is unchanged — the same code that runs in a browser tab runs
 * inside the Electron window, talking to the same Fastify backend over localhost.
 *
 * Authoritative env vars (set by start.script.ts):
 *
 * - FRONTEND_PORT vite's listen port
 * - VITE_FRONTEND_PORT same value, kept for symmetry with the vite-inlined name
 */
import {app, BrowserWindow, ipcMain, shell} from 'electron';
import {spawn} from 'node:child_process';
import {resolve} from 'node:path';

/**
 * Set a stable application identity so Linux desktop environments can match this window to its
 * `.desktop` file (StartupWMClass=agent-storm). On Wayland these don't currently reach the
 * toplevel `app_id` on Electron 42 — the icon/name match is still TODO — but they're cheap and
 * correct under XWayland / X11 sessions, so leave them in.
 */
app.setName('agent-storm');
process.title = 'agent-storm';

const frontendPort = Number(process.env.FRONTEND_PORT ?? process.env.VITE_FRONTEND_PORT);
if (!Number.isInteger(frontendPort) || frontendPort <= 0) {
    console.error(
        'electron: FRONTEND_PORT is not set. Launch via `npm run dev:electron`, which exports it.',
    );
    process.exit(1);
}

const frontendUrl = `http://localhost:${frontendPort}/`;

const preloadPath = resolve(import.meta.dirname, 'preload.cjs');
const iconPath = resolve(import.meta.dirname, '..', 'assets', 'icon.png');

/**
 * Per-launch bearer generated by `start.script.ts` and injected into both this main process
 * and the backend via env. We forward it to the renderer through the preload's
 * `additionalArguments` channel so the frontend never has to show the auth modal — but the
 * backend still verifies it on every request, so this is real authentication, not a bypass.
 *
 * Missing env means start-script didn't run (someone invoked `electron src/main.mjs` directly
 * or env wasn't passed through). Fail loud — silently launching with no auth would defeat the
 * point.
 */
const runtimeSecret = process.env.AGENT_STORM_RUNTIME_SECRET;
if (!runtimeSecret) {
    console.error(
        'electron: AGENT_STORM_RUNTIME_SECRET is not set. Launch via `npm run dev:electron`, ' +
            'which generates and exports it.',
    );
    process.exit(1);
}

async function waitForViteReady(url, timeoutMs = 30_000) {
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
        try {
            const response = await fetch(url);
            if (response.ok) {
                return;
            }
        } catch {
            /* vite isn't listening yet — retry */
        }
        await new Promise((resolve) => setTimeout(resolve, 200));
    }
    throw new Error(`Timed out waiting for vite dev server at ${url}`);
}

async function createWindow() {
    await waitForViteReady(frontendUrl);
    const window = new BrowserWindow({
        width: 1400,
        height: 900,
        title: 'Agent Storm',
        icon: iconPath,
        webPreferences: {
            contextIsolation: true,
            nodeIntegration: false,
            // Enables the <webview> tag used by vir-pr-embed to inline the PR page. GitHub
            // sends `X-Frame-Options: deny`, so a plain <iframe> can't show it — webview runs
            // the page in its own webContents which isn't subject to that header.
            webviewTag: true,
            preload: preloadPath,
            additionalArguments: [`--auth-secret=${runtimeSecret}`],
        },
    });
    /**
     * Lock every <webview> the renderer attaches to the same safe defaults as the main window:
     * no preload, no Node integration, context isolation on. Stops a future change in the
     * renderer (or a future PR-embed reuse) from accidentally widening the attack surface.
     */
    window.webContents.on('will-attach-webview', (_event, webPreferences) => {
        delete webPreferences.preload;
        webPreferences.nodeIntegration = false;
        webPreferences.contextIsolation = true;
    });
    /**
     * Any `window.open(url)` in the renderer (terminal link clicks via WebLinksAddon, sidebar
     * "open PR" action, etc.) should land in the user's *system* browser rather than a new
     * in-app BrowserWindow — embedding lives behind the dedicated <webview> overlay, and the
     * user expects ctrl+click to hand off to Firefox / Chrome / whatever they actually use.
     *
     * We deny the new-window action and forward to `shell.openExternal` ourselves.
     */
    window.webContents.setWindowOpenHandler(({url}) => {
        const parsed = (() => {
            try {
                return new URL(url);
            } catch {
                return null;
            }
        })();
        if (parsed && (parsed.protocol === 'https:' || parsed.protocol === 'http:')) {
            void shell.openExternal(url);
        }
        return {action: 'deny'};
    });
    await window.loadURL(frontendUrl);
}

/**
 * `code <folder>` opens VS Code on the given path. Bridged through IPC so the renderer
 * (which runs with `nodeIntegration: false`) can trigger it without having `child_process` in
 * its global scope. Failures are returned as `{ok: false, error}` rather than thrown so the
 * frontend can surface them as a toast without taking down the renderer.
 */
ipcMain.handle('agent-storm:open-in-vscode', (_event, folderPath) => {
    if (typeof folderPath !== 'string' || folderPath.length === 0) {
        return {ok: false, error: 'invalid folder path'};
    }
    try {
        const child = spawn('code', [folderPath], {
            detached: true,
            stdio: 'ignore',
        });
        child.on('error', (error) => {
            console.error('agent-storm: spawn `code` failed:', error);
        });
        child.unref();
        return {ok: true};
    } catch (error) {
        return {ok: false, error: error instanceof Error ? error.message : String(error)};
    }
});

/**
 * Wire `whenReady` as a callback rather than `await app.whenReady()` at module top level. With
 * Electron 33 in ESM mode, top-level await on `whenReady()` deadlocks: the module's pending await
 * blocks the event loop before the `ready` event can fire, so the promise never resolves.
 */
app.whenReady()
    .then(createWindow)
    .catch((error) => {
        console.error('electron startup failed:', error);
        app.quit();
    });

app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
        void createWindow();
    }
});

app.on('window-all-closed', () => {
    app.quit();
});
